### ISSUE TITLE
madlib image

### ISSUE THREAD

**Issue by drnic** [dingotiles/dingo-postgresql-agent#6]
Can we have a madlib flavor of the docker image?

```
FROM dingotiles/dingo-postgresql:pre-test

RUN pip install pgxnclient
RUN apk run cmake m4 + other things
RUN pgxn install madlib
```

In initial testing this fails with `error: no type named 'string_type'`

Do we need alternate (older) postgresql? Or different base linux?

/cc @cdelashmutt-pivotal @mwright-pivotal

We also played with installing:

* https://wiki.alpinelinux.org/wiki/How_to_get_regular_stuff_working

**Comment by mwright-pivotal** [comment]
I need to do some more testing and possibly remove anything extraneous but this seemed to do the trick
```
FROM dingotiles/dingo-postgresql:pre-test

RUN pip install pgxnclient
RUN echo "http://dl-2.alpinelinux.org/alpine/edge/community" >> /etc/apk/repositories; \
    echo "http://dl-3.alpinelinux.org/alpine/edge/community" >> /etc/apk/repositories; \
    echo "http://dl-4.alpinelinux.org/alpine/edge/community" >> /etc/apk/repositories; \
    echo "http://dl-5.alpinelinux.org/alpine/edge/community" >> /etc/apk/repositories
RUN apk --update add pstree pv geos proj4 gdal
RUN apk --update add m4
RUN apk --update add build-base gcc abuild binutils binutils-doc gcc-doc
RUN apk --update add cmake cmake-doc
RUN pgxn install madlib
```

**Comment by drnic** [comment]
@mwright-pivotal awesome!

If there is any interesting tutorials or "next steps" you'd like ppl to try, let's start by putting them into https://github.com/dingotiles/dingo-postgresql-agent/blob/master/images/postgresql95-madlib/README.md

Then I'll migrate them to https://hub.dingotiles.com/tutorial or a new page.

**Comment by drnic** [comment]
The madlib image will be continously rebuilt by CI; currently its built off `:pre-test` in the middle of the pipeline. In future I might move it to be built after/during `shipit`; and versioned/tagged to match the base image.

https://ci.starkandwayne.com/teams/main/pipelines/dingo-postgresql-agent/jobs/madlib-image/builds/3

**Comment by drnic** [comment]
Note to self: the hub should record the `DINGO_IMAGE_NAME` as well for record keeping and to help with support.

**Comment by drnic** [comment]
```
$ psql $(docker exec -ti dingo-postgresql cat /config/uri) -c "create extension madlib;"
ERROR:  required extension "plpythonu" is not installed
```

**Comment by drnic** [comment]
Ok there's now a separate docker image layer for installing postgresql from a `dingotiles/dingo-postgresql-base:latest` image (that doesn't have postgresql in it).

We can try replacing the middle layer with "build pg from source including `--with-python` here:

https://github.com/dingotiles/dingo-postgresql-agent/blob/master/images/postgresql95-base/Dockerfile

**Comment by drnic** [comment]
So I built postgresql from source with `./configure --with-python PYTHON=/usr/bin/python3` flags; and so now `create extension plpython3u;` works but that doesn't make `madlib` happy:

```
postgres=# create extension plpython3u;
CREATE EXTENSION
postgres=# create extension madlib;
ERROR:  required extension "plpythonu" is not installed
```

Is `madlib` hardcoded to only support python2?

**Comment by drnic** [comment]
https://cwiki.apache.org/confluence/display/MADLIB/Installation+Guide `MADlib works with Python 2.6 and 2.7.  Currently, Python 3.x is not supported.` Blah.

**Comment by drnic** [comment]
Ok, building postgresql --with-python for python2 and plpythonu/madlib extensions install. Will reconfigure the docker images & ci pipeline that produces them tomorrow. Need to think thru what flavor of postgresql goes into each base image. Only madlib needs plpythonu which needs python2.

**Comment by drnic** [comment]
![screen shot 2017-03-21 at 9 12 55 am](https://cloud.githubusercontent.com/assets/108/24125872/9a61ad44-0e16-11e7-8f4e-d5d903a0bb2e.png)

https://ci.starkandwayne.com/teams/main/pipelines/dingo-postgresql-agent?groups=madlib

WIP pipeline to create base madlib image (pg95 from source, plus python2) and final madlib images that include dingo agent etc and then run thru normal test suite to ensure it still "just works".

**Comment by drnic** [comment]
Hurray! madlib image is now published in sync with normal/postgis image via `shipit` job. v0.0.11 has been released!

![screen shot 2017-03-21 at 10 01 19 am](https://cloud.githubusercontent.com/assets/108/24127040/6b27d8d0-0e1d-11e7-9dbb-756f4d02c509.png)

https://github.com/dingotiles/dingo-postgresql-agent/releases/tag/v0.0.11

Thanks again @mwright-pivotal !!

**Comment by mwright-pivotal** [comment]
very nice!   thanks for turning this around so quickly.   

I was able to use your latest image to run:

/usr/local/madlib/bin/madpack -p postgres -c superuser-username@myhost/postgres install remotely from my laptop.  This finishes the registration of the MADlib algorithms (functions).

From there, I used this http://greenplum.org/gpdb-sandbox-tutorials/ to validate running an algorithm after tweaking the SQL syntax to remove GPDB specific clauses.  

After grabbing the latest airline on time performance from https://www.transtats.bts.gov/DL_SelectFields.asp?Table_ID=236, I am able to run the comparison between American and Delta:

postgres=# select carrier, count(*) from faa.faa_otp_load group by carrier;
 carrier | count  
---------+--------
 HA      |   6276
 DL      |  69813
 EV      |  35037
 AS      |  14711
 NK      |  12570
 VX      |   5782
 OO      |  50146
 B6      |  24602
 WN      | 107785
 UA      |  42403
 F9      |   7760
 AA      |  73132
(12 rows)

postgres=# SELECT (MADlib.one_way_anova (
CASE WHEN carrier = 'AA' THEN 1
WHEN carrier = 'DL' THEN 2
ELSE NULL
END,
arrdelayminutes
)).* FROM faa.faa_otp_load;

sum_squares_between | sum_squares_within | df_between | df_within | mean_squares_between | mean_squares_within |    statistic     |       p_value        
---------------------+--------------------+------------+-----------+----------------------+---------------------+------------------+----------------------
    367571.494625655 |   300529151.103718 |          1 |    140787 |     367571.494625655 |    2134.63708370601 | 172.193904730402 | 2.58896258881674e-39
(1 row)

which shows a very small p-value here.

**Comment by drnic** [comment]
That's awesome.
Is it ok if I use that for a madlib tutorial page?






On Tue, Mar 21, 2017 at 1:08 PM +1000, "Mike Wright" <notifications@github.com> wrote:












very nice!   thanks for turning this around so quickly.


I was able to use your latest image to run:


/usr/local/madlib/bin/madpack -p postgres -c superuser-username@myhost/postgres install remotely from my laptop.  This finishes the registration of the MADlib algorithms (functions).


From there, I used this http://greenplum.org/gpdb-sandbox-tutorials/ to validate running an algorithm after tweaking the SQL syntax to remove GPDB specific clauses.


After grabbing the latest airline on time performance from https://www.transtats.bts.gov/DL_SelectFields.asp?Table_ID=236, I am able to run the comparison between American and Delta:


postgres=# select carrier, count(*) from faa.faa_otp_load group by carrier;

carrier | count

---------+--------

HA      |   6276

DL      |  69813

EV      |  35037

AS      |  14711

NK      |  12570

VX      |   5782

OO      |  50146

B6      |  24602

WN      | 107785

UA      |  42403

F9      |   7760

AA      |  73132

(12 rows)


postgres=# SELECT (MADlib.one_way_anova (

CASE WHEN carrier = 'AA' THEN 1

WHEN carrier = 'DL' THEN 2

ELSE NULL

END,

arrdelayminutes

)).* FROM faa.faa_otp_load;


sum_squares_between | sum_squares_within | df_between | df_within | mean_squares_between | mean_squares_within |    statistic     |       p_value

---------------------+--------------------+------------+-----------+----------------------+---------------------+------------------+----------------------

367571.494625655 |   300529151.103718 |          1 |    140787 |     367571.494625655 |    2134.63708370601 | 172.193904730402 | 2.58896258881674e-39

(1 row)


which shows a very small p-value here.
